application: my-route-planner
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /css
  static_dir: static/css

- url: /swf
  static_dir: static/swf
  
- url: /qunit
  static_dir: test/qunit

- url: /js
  static_dir: static/js
  
- url: /img
  static_dir: static/images
  
- url: /(.*\.(gif|png|jpg|ico|js|css|xml|txt|xlsx))$
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|xml|txt|xlsx))
  
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always  
  
- url: /auth/.*
  script: handler.auth.app
  secure: always
  
- url: /team_admin/.*
  script: handler.team_admin.app
  secure: always  
  
- url: /team_user/.*
  script: handler.team_user.app
  secure: always  

- url: /group_admin/.*
  script: handler.group_admin.app
  secure: always  
  
- url: /sys_admin/.*
  script: handler.sys_admin.app
  secure: always  

- url: /super_admin/.*
  script: handler.super_admin.app
  secure: always
  
- url: /test/.*
  script: test.app

- url: /.*
  script: handler.main.app
  secure: always  

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
    
libraries:
- name: webapp2
  version: latest
  
- name: jinja2
  version: latest
  
builtins:
- deferred: on