application: my-best-route
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /css
  static_dir: static/css
  
- url: /test
  static_dir: test

- url: /qunit
  static_dir: test/qunit

- url: /js
  static_dir: static/js
  
- url: /img
  static_dir: static/images
  
- url: /(.*\.(gif|png|jpg|ico|js|css|xml|txt))$
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|xml|txt))

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
  
- name: jinja2
  version: latest
 